<?php
/**
 * The template for displaying product content within loops
 *
 * This template MUST ONLY contain the standard WooCommerce action hooks.
 * The actual HTML structure is generated by functions hooked into these actions
 * within inc/woocommerce.php.
 *
 * @see     https://woocommerce.com/document/template-structure/
 * @package WooCommerce
 * @version 3.6.0 
 */

defined('ABSPATH') || exit;

global $product;

// Ensure visibility.
if ( empty( $product ) || ! $product->is_visible() ) {
	return;
}
?>
<li <?php wc_product_class( '', $product ); ?>>
	<?php
	/**
	 * Hook: woocommerce_before_shop_loop_item.
	 *
	 * @hooked cuevas_product_card_open - 5 (outputs opening divs, link, image container, badges)
	 * @hooked woocommerce_template_loop_product_link_open - 10 (removed)
	 */
	do_action( 'woocommerce_before_shop_loop_item' );

	/**
	 * Hook: woocommerce_before_shop_loop_item_title.
	 *
	 * @hooked woocommerce_show_product_loop_sale_flash - 10 (removed, handled by cuevas_product_card_open)
	 * @hooked woocommerce_template_loop_product_thumbnail - 10 (removed)
     * @hooked cuevas_product_card_image - 10 (outputs image tag)
     * @hooked cuevas_product_card_info_open - 20 (closes image container, opens info container, outputs title)
	 */
	do_action( 'woocommerce_before_shop_loop_item_title' );

	/**
	 * Hook: woocommerce_shop_loop_item_title.
     *
     * @hooked woocommerce_template_loop_product_title - 10 (removed, handled by cuevas_product_card_info_open)
	 */
	do_action( 'woocommerce_shop_loop_item_title' );

	/**
	 * Hook: woocommerce_after_shop_loop_item_title.
	 *
	 * @hooked woocommerce_template_loop_rating - 5 (removed)
	 * @hooked woocommerce_template_loop_price - 10 (removed)
     * @hooked cuevas_product_card_price_button - 10 (outputs price and add-to-cart button)
	 */
	do_action( 'woocommerce_after_shop_loop_item_title' );

	/**
	 * Hook: woocommerce_after_shop_loop_item.
	 *
	 * @hooked woocommerce_template_loop_product_link_close - 5 (removed)
	 * @hooked woocommerce_template_loop_add_to_cart - 10 (removed)
     * @hooked cuevas_product_card_close - 15 (closes info container, link, and card div)
	 */
	do_action( 'woocommerce_after_shop_loop_item' );
	?>
</li> 